version: "3"

services:
  mysql:
    image: mysql:8.1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Archeage
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
  elasticsearch:
    image: elasticsearch:8.11.1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  docker:
    image: docker:24.0.7-dind-alpine3.19
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      jenkins_net:
    volumes:
      - jenkins_data:/var/jenkins_home
      - jenkins_docker_certs:/certs/client
    ports:
      - "2376:2376"
  jenkins:
    build:
      dockerfile: JenkinsDockerfile
    environment:
      - JENKINS_OPTS=--httpPort=8085
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    networks:
      jenkins_net:
    volumes:
      - jenkins_data:/var/jenkins_home
      - jenkins_docker_certs:/certs/client:ro
    ports:
      - "8085:8085"
#  prometheus:
#    image: bitnami/prometheus:latest
#    ports:
#      - "9090:9090"
#    volumes:
#      - prometheus_data:/opt/bitnami/prometheus/data
#      - ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
networks:
  jenkins_net:
volumes:
  mysql_data:
  prometheus_data:
  elasticsearch_data:
  jenkins_data:
  jenkins_docker_certs: