version: "3"

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Archeage
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
  elasticsearch:
    image: elasticsearch:8.11.1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    environment:
      - JENKINS_OPTS=--httpPort=8085
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/var/jenkins_home
    ports:
      - "8085:8085"
#  prometheus:
#    image: bitnami/prometheus:latest
#    ports:
#      - "9090:9090"
#    volumes:
#      - prometheus_data:/opt/bitnami/prometheus/data
#      - ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
networks:
  jenkins:
volumes:
  mysql_data:
  prometheus_data:
  elasticsearch_data:
  jenkins_data: