spring:
  cloud:
    gateway:
      routes:
        - id: price_route
          uri: http://localhost:8090
          predicates:
            - Host={server}.price.localhost:8070
          filters:
            - AddRequestHeader=X-ARCHEAGE-SERVER,{server}
        - id: web_route
          uri: http://localhost:8080
          predicates:
            - Host=app.localhost:8070
        - id: data_route
          uri: http://localhost:8085
          predicates:
            - Host=data.localhost:8070
      default-filters:
debug: true