spring:
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: http://localhost:8090
          predicates:
            - Host={server}.localhost:8070
          filters:
            - AddRequestHeader=X-ARCHEAGE-SERVER,{server}
debug: true