create table recipe_materials (quantity integer not null, item_id bigint not null, recipe_id bigint not null, primary key (item_id, recipe_id)) engine=InnoDB;
create table item_prices (copper integer not null, gold integer not null, silver integer not null, id bigint not null, item_id bigint not null, archeage_server_id bigint not null, timestamp datetime(6), primary key (id)) engine=InnoDB;
create table item_prices_seq (next_val bigint) engine=InnoDB;
insert into item_prices_seq values ( 1 );
create table items (id bigint not null, description TEXT, name varchar(255), region enum ('CIS','EUROPE'), primary key (id)) engine=InnoDB;
create table items_sequence_generator (next_val bigint) engine=InnoDB;
insert into items_sequence_generator values ( 1 );
create table locations (has_factory bit not null, id bigint not null, continent enum ('EAST','NORTH','WEST'), name varchar(255), region enum ('CIS','EUROPE'), primary key (id)) engine=InnoDB;
create table locations_sequence_generator (next_val bigint) engine=InnoDB;
insert into locations_sequence_generator values ( 1 );
create table pack_price (id bigint not null, sell_location_id bigint not null, primary key (id)) engine=InnoDB;
create table packs (creation_location_id bigint not null, id bigint not null, primary key (id)) engine=InnoDB;
create table recipes (produced_quantity integer not null, craftable_id bigint, id bigint not null, primary key (id)) engine=InnoDB;
create table recipes_sequence_generator (next_val bigint) engine=InnoDB;
insert into recipes_sequence_generator values ( 1 );
create table archeage_server (id bigint not null, name varchar(255), region enum ('CIS','EUROPE'), primary key (id)) engine=InnoDB;
create table archeage_server_seq (next_val bigint) engine=InnoDB;
insert into archeage_server_seq values ( 1 );
create table users (id bigint not null, email varchar(255), password varchar(255), role enum ('ADMIN','USER'), primary key (id)) engine=InnoDB;
create table users_id_sequence_generator (next_val bigint) engine=InnoDB;
insert into users_id_sequence_generator values ( 1 );
alter table items add constraint ITEMS_UNIQUE_NAME_CONSTRAINT unique (name);
alter table recipe_materials add constraint FKl24g8bw11xtarq11hvxm8sxi8 foreign key (item_id) references items (id);
alter table recipe_materials add constraint FKe5wa9q3i5l5o7g9jnmauoqhx0 foreign key (recipe_id) references recipes (id);
alter table item_prices add constraint FKnclijija00rm8bi7jjk95j5x6 foreign key (item_id) references items (id);
alter table item_prices add constraint FKmgn09q8kfyc4oyjocu0caafh8 foreign key (archeage_server_id) references archeage_server (id);
alter table pack_price add constraint FKooskfakl155d36aepnsturonm foreign key (sell_location_id) references locations (id);
alter table pack_price add constraint FKa2lcm5xgp3u9dpxbcxwd04u5f foreign key (id) references item_prices (id);
alter table packs add constraint FK1xi3vivn5vbkpsptcme6e4ovy foreign key (creation_location_id) references locations (id);
alter table packs add constraint FKjml7yq3pqca98ugehgx0ul48k foreign key (id) references items (id);
alter table recipes add constraint FK3j7mnbptd1qayblp29pnqgy5l foreign key (craftable_id) references items (id);
